# This is a basic workflow to help you get started with Actions

name: Download _all_docs_with_include_docs endpoint

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        skip: [0, 100000, 200000, 300000]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Download all packages from the _all_docs endpoints
        env:
          SKIP: ${{ matrix.skip }}
        run: |
              curl --compressed --retry 100 "https://replicate.npmjs.com/_all_docs?limit=100000&include_docs=true&skip=${SKIP}" -o "_all_docs_include_docs_${SKIP}.json" && \
              jq -c '.rows[].doc | {name: .versions[.["dist-tags"].latest].name, version: .["dist-tags"].latest, scripts: .versions[.["dist-tags"].latest].scripts}' "_all_docs_include_docs_$SKIP.json" | grep -E "\"\s*(((pre|post)*(prepare|install))|prepublish)\s*\":" | jq -c "{name: .name, version: .version, scripts: .scripts | keys | sort}" > "_all_docs_include_docs_${SKIP}_scripts.ljson" && \
              du -hs * && \
              wc -l "_all_docs_include_docs_${SKIP}_scripts.ljson" && \
              cat "_all_docs_include_docs_${SKIP}_scripts.ljson";



