# This is a basic workflow to help you get started with Actions

name: Download _all_docs endpoint

# Controls when the action will run. 
on:
  schedule:
  - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Download all packages from the _all_docs endpoints
        run: |
              curl --compressed --retry 100 "https://replicate.npmjs.com/_all_docs" -o _all_docs.json && \
              jq -r .rows[].key < _all_docs.json > all_package_names.txt;
              git config --global user.name "github-actions[bot]";
              git config --global user.email "933164984+github-actions[bot]@users.noreply.github.com";
              git add all_package_names.txt;
              git commit -m "Update package names";
              git push;
